#! /bin/bash

# This is a helper script which builds the YaST Docker container and starts
# the specified YaST module there. It bind-mounts the host system into the
# container so YaST can change the chost system through that.
#
# This script runs the YaST module with ncurses (text mode) UI.

set -ex

# target container name
CONTAINER_NAME="yast-mgmt-ncurses"

VERSION=`(. /etc/os-release && echo "$VERSION")`
# base OS for the Docker image
: "${DOCKER_BASE_IMAGE=opensuse/leap:$VERSION}"

# build the docker image first (it reuses the built image in the next run)
docker build --build-arg image="$DOCKER_BASE_IMAGE" -t "$CONTAINER_NAME" .

# start the container with extra "-e" and "-v" options to allow accessing
# the local X server from inside the Docker container
docker run -it -v "/:/mnt" --privileged --pid=host --ipc=host --hostname yast-container \
    --rm "$CONTAINER_NAME" /sbin/yast "$@"
