#! /bin/bash

# This is a helper script which builds the YaST Docker container and starts
# the specified YaST module there. It bind-mounts the host system into the
# container so YaST can change the chost system through that.
#
# This script runs the YaST module with Qt (graphical) UI so it needs a running
# X server.

set -ex

# target container name
CONTAINER_NAME="yast-mgmt-qt"

if command -v podman &> /dev/null; then
    COMMAND="podman"
elif command -v docker &> /dev/null; then
    COMMAND="docker"
else
    echo "ERROR: Container runtime not installed, install 'podman' or 'docker' package" >&2
    exit 1
fi

# VERSION=`(. /etc/os-release && echo "$VERSION")`
# The used patches are against 15.4
VERSION=15.4

# base OS for the Docker image
: "${DOCKER_BASE_IMAGE=opensuse/leap:$VERSION}"

# make sure the base image is up to date
$COMMAND build --build-arg image="$DOCKER_BASE_IMAGE" -t yast-mgmt-ncurses .
# build the docker image first (it reuses the built image in the next run)
$COMMAND build -t "$CONTAINER_NAME" -f Dockerfile_qt .

# start the container with extra "-e" and "-v" options to allow accessing
# the local X server from inside the Docker container
$COMMAND run -it -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro --net=host \
    -v "$XAUTHORITY:$XAUTHORITY:ro" -e XAUTHORITY \
    -e ZYPP_LOCKFILE_ROOT=/mnt -e YAST_SCR_TARGET=/mnt -v "/:/mnt" \
    --privileged --pid=host --ipc=host --rm "$CONTAINER_NAME" /sbin/yast2 "$@"
